baseURL = "https://elizurhz.cn/"
languageCode = "zh-CN"
title = "Variation Palladion - 撕裂时间的帕拉迪昂"

theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
publishDir = "docs"

preserveTaxonomyNames = true

[Permalinks]
  posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Web 前端"
    url = "/frontend/"
    weight = 1
    
  [[menu.main]]
    name = "移动开发"
    url = "/mobile/"
    weight = 2

  [[menu.main]]
    name = "后端/运维/部署"
    url = "/backend/"
    weight = 2

  [[menu.main]]
    name = "开发杂谈"
    url = "/by-talk/"
    weight = 1

  [[menu.main]]
    name = "其他技术"
    url = "/tips/"
    weight = 3

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 97

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 98

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 99

[params]
    since = 2019
    author = "Haoze Harry Xu"                           # Author's name
    avatar = "/images/me/avatar.png"           # Author's avatar
    subtitle = "温馨提示：点击左上角的心可切换成暗黑模式。本 Blog 的 GitHub 仓库已开启 Discussion，详见顶部导航的 “About” 栏目"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可：全文转载需要本人许可，如有引用需署名。'

[params.social]
    GitHub = "ElizurHz"
    Email = "elizurhz@gmail.com"
    # Instagram = "elizur_hz"
    # Wechat = "/images/me/wechat.jpg"  # Wechat QRcode image
    # Facebook = "elizurhz"
    # Telegram = "xxoo"
    # Dribbble = "xxoo"
    # Medium = "xxoo"
